baseURL = 'https://cspeoplescoalition.org/'
author = 'Ali "Magpie" Rook'
copyright = 'made with love in colorado springs by ali "magpie" rook'
languageCode = 'en-us'
hasCJKLanguage = true
defaultContentLanguage = 'en'
title = 'CS Peoples Coalition'
paginate = 10
enableRobotsTXT = true
enableEmoji = true
theme = 'cspc-tailwind'

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
