baseURL = 'https://cspeoplescoalition.org/'
author = 'Ali "Magpie" Rook'
copyright = 'made with love in colorado springs by ali "magpie" rook'
languageCode = 'en-us'
hasCJKLanguage = true
defaultContentLanguage = 'en'
title = 'CS Peoples Coalition'
theme = 'tailwind'
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]
enableRobotsTXT = true
enableEmoji = true

[markup]
[markup.highlight]
  lineNos = true
  noClasses = false
[markup.goldmark]
  [markup.goldmark.renderer]
    unsafe = true

[privacy]
  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[module]
  [module.hugoVersion]
    extended = false
    min = "0.120.0"
