# SEO keywords and description for your site.
keywords = "cs, cos, co, colorado, springs, colorado springs, leftist, people, coalition, peoples coalition, socialist"
subtitle = "The homepage for Colorado Springs Peoples Coalition"

# dir name of your blog content (default is `content/posts`).
# the list of set content will show up on your index page (baseurl).
contentTypeName = "posts"

# Show table of contents at the top of your posts (defaults to false)
# Alternatively, add this param to post front matter for specific posts
toc = false

showReadingTime = false

[header]
  logo = "cspc-logo-darkmode.webp"
  darklogo = "cspc-logo.webp"
  sticky = true

[footer]
  since = 2024
  poweredby = true

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

  [taxonomies.icons]
    categories = "category-2"
    tags = "hash"

# giscus is comments system powered by GitHub Discussions
# generate configurations from https://giscus.app/
[giscus]
  enabled = true
  repo = "cospc/cspeoplescoalition.org"
  repoID = "R_kgDOLGt_zw"
  category = "Comments"
  categoryID = "DIC_kwDOLGt_z84Cchln"
  mapping = "pathname"
  strict = "0"
  reactionsEnabled = "1"
  emitMetadata = "1"
  inputPosition = "bottom"
  lang = "en"

[social_media]
  [[social_media.items]]
    enabled = true
    title = 'Facebook'
    icon = 'brand-facebook'
    link = 'https://www.facebook.com/CSPC719'

  [[social_media.items]]
    enabled = false
    title = 'Twitter'
    icon = 'brand-x'
    link = 'https://twitter.com/'

  [[social_media.items]]
    enabled = true
    title = 'Instagram'
    icon = 'brand-instagram'
    link = 'https://www.instagram.com/cospeoplescoalition'

  [[social_media.items]]
    enabled = false
    title = 'LinkedIn'
    icon = 'brand-linkedin'
    link = 'https://www.linkedin.com/'

  [[social_media.items]]
    enabled = true
    title = 'Github'
    icon = 'brand-github'
    link = 'https://github.com/cospc'
